before_install:
    - sudo apt-get -y update
    - sudo apt-get install -y python3-pip libxml2-dev libxslt1-dev python3-dev cython zlib1g-dev
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install --upgrade pip
    - sudo pip3 install -r requirements-pip-dev.txt
