image: python:3.9

pipelines:
  default:
    - step:
        name: install
        caches:
          - pip
        script:
          - pip install -r requirements-pip-dev.txt

    - step:
        name: Test
        script:
          - pytest -v tests/* --junitxml=test-reports/report.xml
          
    - step:
      name: Release
      script:
          - python ./automation/new_release.py && python setup.py sdist bdist_wheel && twine upload --username="${TWINE_USERNAME}" --password="${TWINE_PASSWORD}" dist/*
