image: ubuntu:20.04

pipelines:
  default:
    - step:
        name: Install OS depencencies
        script:
          - apt update
          - apt install python3-pip git --yes
          - pip3 install -U pip wheel
          - pip3 install ansible
    - step:
        name: Install ansible-playbook
        script:
          - ansible-playbook --connection=local automation/ansible/dev_playbook.yaml

    - step:
        name: Install python dependencies
        caches:
          - pip
        script:
          - pip install -r requirements-pip-dev.txt

    - step:
        name: Test
        script:
          - pytest -v tests/* --junitxml=test-reports/report.xml
          
    - step:
        name: Release
        script:
          - python ./automation/new_release.py && python setup.py sdist bdist_wheel && twine upload --username="${TWINE_USERNAME}" --password="${TWINE_PASSWORD}" dist/*
