#name: Custolint
on:
  push:
    #branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - run: python -m venv .venv
      - run: source .venv/bin/activate && make update_pip_and_wheel install_dev
      - uses: actions/cache@v3
        with:
          path: .venv
          key: a-key

  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: a-key
      - run: source .venv/bin/activate && make pytest

  pypi_publish:
    if: github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ciur
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - run: make update_pip_and_wheel install_prod wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  docker:
    if: github.event.pull_request.merged == true
    needs: pypi_publish
    runs-on: ubuntu-latest
    environment:
      name: hub.docker.com
      url: https://hub.docker.com/repositories/adan
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/prod/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: adan/ciur:0.2.1.dev2
